version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    expose: 
      - "9000"
    restart: on-failure

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/aboulest/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: bind
      device: /home/aboulest/data/mariadb

networks:
    inception:
      driver: bridge